### ISSUE TITLE
Character vector on x-axis and numeric vector on y axis

### ISSUE THREAD

**Issue by dnchari** [hrbrmstr/metricsgraphics#17]
I am unable to plot character vector and corresponding numeric vector.

**Comment by hrbrmstr** [comment]
Can you provide a small example?

**Comment by dnchari** [comment]
iris %>%
mjs_plot(x=Species, y=Sepal.Length) %>% mjs_bar() 

iris %>%
mjs_plot(x=Species, y=Sepal.Length) %>% mjs_line()

**Comment by dnchari** [comment]
iris %>%group_by(Species) %>% summarise(Sepal=sum(Sepal.Length))%>%
 mjs_plot(x=Species, y=Sepal) %>%
mjs_bar()

**Comment by hrbrmstr** [comment]
The MetricsGraphics.js bar charts API is unstable (it has changed numerous times since starting this package) and I won't be putting effort into it until it stabilizes. That means you can only do horizontal bar charts:

    iris %>%
      mjs_plot(x=Sepal.Length, y=Species) %>% mjs_bar()

and, even then, it's geared towards display metrics (hence the name of the JavaScript library having "metrics" in it). The need for the bullet-chart-type lines is a new 2.1.0 feature and immutable (not my fault).

MetricsGraphics.js line charts do not support generalized text labels. From the MetricsGraphics.js main site:

>MetricsGraphics.js is a library built on top of D3 that is optimized for visualizing and laying out time-series data.

So, it's not a general purpose charting library. That's more what `ggvis` is supposed to be.

**Comment by dnchari** [comment]
Thank you and thanks for your great work
